### PR TITLE
Fix refrigerated case and walkin defrost and dripdown schedule values

### LINKED ISSUE #1646: Refrigeration system defrost/dripdown schedules always zero
Defrost and dripdown schedules for[ refrigerated cases](https://github.com/NREL/openstudio-standards/blob/cea7e58bd4af6a7bf51d26ef697c473b2f2e2258/lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb#L604-L633) and [walk-in coolers](https://github.com/NREL/openstudio-standards/blob/cea7e58bd4af6a7bf51d26ef697c473b2f2e2258/lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb#L690-L719) are never assigned a value other than zero, and thus never initiate defrost or drip-down operation.

### PR DESCRIPTION
**Pull request by mdahlhausen**
Pull request overview
---------------------
Renames defrost and dripdown schedules for refrigerated cases and walkins. Sets those schedules to 1 when operating for typical refrigeration.

 - Fixes #1646 

### Pull Request Author
 - [x] Method changes or additions
 - [x] Resolved yard documentation errors for new code (ran `bundle exec rake doc`)
 - [x] Resolved rubocop syntax errors for new code (ran `bundle exec rake rubocop`)
 - [x] All new and existing tests passes

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [x] Perform a code review on GitHub
 - [x] All related changes have been implemented: method additions, changes, tests
 - [x] Check rubocop errors
 - [x] Check yard doc errors
 - [x] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [x] CI status: all green or justified

### CODE REVIEW

File: lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb [hunk 1]
```diff
@@ -612,11 +612,11 @@ def model_add_typical_refrigeration(model, building_type)
 
         # Add defrost and dripdown schedules
         defrost_sch = OpenStudio::Model::ScheduleRuleset.new(model)
-        defrost_sch.setName('Refrigeration Defrost Schedule')
-        defrost_sch.defaultDaySchedule.setName("Refrigeration Defrost Schedule Default - #{case_type}")
+        defrost_sch.setName("#{ref_case.name} Refrigeration Defrost Schedule")
```
Comment (eringold) [inline lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb:615]: IMO 'Refrigeration' (and perhaps even 'Schedule') don't add anything to these schedule names and can make them hard to use in the app. But not a huge deal.

Comment (mdahlhausen) [reply lib/openstudio-standards/prototypes/common/objects/Prototype.refrigeration.rb]: shortened the names

**Review by eringold — APPROVED** [review]
