### PR TITLE
Fix PTHP capacity and VAV minimum damper calculation issues

### LINKED ISSUE #1590: Error in Standards.AirLoopHVAC - no implicit conversion from nil to integer
Hello All,

I have been debugging a fairly large model for which I am trying to perform a sizing run and then set the efficiencies and controls of a VAV air loop based on them. The process is failing in the stage of `air_loop_hvac_adjust_minimum_vav_damper_positions` and I'm trying to figure out if there is something that I can change about my model to get it to succeed.

I am struggling to get to a minimal sample file that recreates the case and I will post it here if I get there since I know that would be valuable to you for debugging. But I was hoping that maybe the full traceback might be more legible to someone here. Or, in the event this is a recognizable bug or an exception that can be caught, it would be really nice to have the method proceed in future versions of the standards gem.

Here is the full traceback:
```
[18:01:43.058781 ERROR] no implicit conversion from nil to integer
:/ruby/2.7.0/gems/openstudio-standards-0.3.0/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb:2144:in `min'
:/ruby/2.7.0/gems/openstudio-standards-0.3.0/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb:2144:in `air_loop_hvac_adjust_minimum_vav_damper_positions'
:/ruby/2.7.0/gems/openstudio-standards-0.3.0/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb:18:in `air_loop_hvac_apply_multizone_vav_outdoor_air_sizing'
:/ruby/2.7.0/gems/openstudio-standards-0.3.0/lib/openstudio-standards/standards/Standards.Model.rb:2257:in `block in model_apply_multizone_vav_outdoor_air_sizing'
:/ruby/2.7.0/gems/openstudio-standards-0.3.0/lib/openstudio-standards/standards/Standards.Model.rb:2257:in `each'
:/ruby/2.7.0/gems/openstudio-standards-0.3.0/lib/openstudio-standards/standards/Standards.Model.rb:2257:in `model_apply_multizone_vav_outdoor_air_sizing'
/home/ladybugbot/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/measures/from_honeybee_model/measure.rb:173:in `run'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:517:in `apply_measure'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:114:in `block in apply_measures'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:67:in `each_index'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:291:in `step'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:233:in `run'
:/openstudio_cli.rb:1184:in `execute'
:/openstudio_cli.rb:814:in `execute'
:/openstudio_cli.rb:1983:in `<main>'
eval:188:in `eval'
eval:188:in `require_embedded_absolute'
eval:173:in `block in require_embedded'
eval:167:in `each'
eval:167:in `require_embedded'
eval:126:in `require'
eval:3:in `<main>'
```

Do you have any thoughts on what might be going on to result in a Nil value at this stage of the process? Is the sizing calculation returning zero load or something like that?

Any advice would be appreciated and, again, if I manage to narrow down the problematic zones amid this 760-Zone model, I will post a minimal sample file here to recreate the issue.

### PR DESCRIPTION
**Pull request by mdahlhausen**
Pull request overview
---------------------
This issues handles two edge cases, one with PTHPs having undefined capacity, and the other where there is no outdoor or zone design airflow rate when setting the minimum vav damper position.
 - Fixes #1590 

### Pull Request Author
 - [x] Method changes or additions
 - [x] Documented new methods using [yard syntax](https://rubydoc.info/gems/yard/file/docs/GettingStarted.md)
 - [x] Resolved yard documentation errors for new code (ran `bundle exec rake doc`)
 - [x] Resolved rubocop syntax errors for new code (ran `bundle exec rake rubocop`)
 - [ ] All new and existing tests passes

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [x] Perform a code review on GitHub
 - [x] All related changes have been implemented: method additions, changes, tests
 - [x] Check rubocop errors
 - [x] Check yard doc errors
 - [x] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] CI status: all green or justified

### CODE REVIEW

File: lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb [hunk 1]
```diff
@@ -2135,7 +2139,7 @@ def air_loop_hvac_adjust_minimum_vav_damper_positions(air_loop_hvac)
       v_dz = v_pz * mdp
 
       # Zone discharge air fraction
-      z_d = v_oz / v_dz
+      z_d = (v_dz.zero? || v_oz.zero?) ? 0.0 : v_oz / v_dz
```
Comment (eringold) [inline lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb:2142]: `v_pz` shows up in the denominator again below in line 2164, which should also guard against `v_pz.zero?`

File: lib/openstudio-standards/standards/Standards.CoilHeatingDXSingleSpeed.rb [hunk 2]
```diff
@@ -133,12 +133,23 @@ def coil_heating_dx_single_speed_standard_minimum_cop(coil_heating_dx_single_spe
...
-      # If the unit's capacity is greater than 15,000 Btu/h, use 15,000 Btu/h in the calculation.
-      capacity_btu_per_hr = 7000 if capacity_btu_per_hr < 7000
-      capacity_btu_per_hr = 15_000 if capacity_btu_per_hr > 15_000
+
+      # If the unit's capacity is nil or less than 7000 Btu/h, use 7000 Btu/h in the calculation
+      # If the unit's capacity is greater than 15,000 Btu/h, use 15,000 Btu/h in the calculation
+      if capacity_btu_per_hr.nil?
+        capacity_btu_per_hr = 7000.0
+        capacity_kbtu_per_hr = capacity_btu_per_hr / 1000.0
+        OpenStudio.logFree(OpenStudio::Warn, 'openstudio.standards.CoilHeatingDXSingleSpeed', "Cooling Capacity for #{coil_heating_dx_single_speed.name}: #{sub_category} is nil. This zone may not have heating. Using default equipment efficiency for a 7 kBtu/hr unit.")
```
Comment (eringold) [inline lib/openstudio-standards/standards/Standards.CoilHeatingDXSingleSpeed.rb:142]: Log messages should say 'heating capacity'

**Review by eringold — CHANGES_REQUESTED** [review]

File: lib/openstudio-standards/standards/Standards.CoilHeatingDXSingleSpeed.rb (hunk 2 above)
Comment (mdahlhausen) [reply lib/openstudio-standards/standards/Standards.CoilHeatingDXSingleSpeed.rb:142]: Per 90.1 _"'Cap' means the rated cooling capacity of the product in Btu/h. If the unit’s capacity is less than 7000 Btu/h, use 7000 Btu/h in the calculation. If the unit’s capacity is greater than
15,000 Btu/h, use 15,000 Btu/h in the calculation."_
So cooling capacity is correct. I added an informative note to the message about it.

File: lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb (hunk 1 above)
Comment (mdahlhausen) [reply lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb:2142]: added a guard clause to line 2164

**Review by eringold — APPROVED** [review]
